# Generated by Django 3.2 on 2021-05-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('occupied', 'Occupied'), ('available', 'Available')], max_length=9)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PersonApp.person')),
            ],
        ),
    ]
