# Generated by Django 3.2 on 2021-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('cc', 'CC'), ('ce', 'CE'), ('pe', 'PE'), ('ti', 'TI')], max_length=2)),
                ('document_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
