# Generated by Django 3.2 on 2021-05-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MenuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('available', 'Available'), ('exhausted', 'Exhausted')], max_length=12)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MenuApp.section')),
            ],
        ),
    ]
