# Generated by Django 3.2 on 2021-05-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('name_section', models.CharField(max_length=150)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MenuApp.menu')),
            ],
        ),
    ]
