# Generated by Django 3.2 on 2021-05-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name_section',
            new_name='name',
        ),
    ]
