# Generated by Django 3.2 on 2021-05-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonApp', '0001_initial'),
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('stage', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], max_length=11)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PersonApp.person')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductApp.product')),
            ],
        ),
    ]
