# Generated by Django 3.2 on 2021-05-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderApp', '0001_initial'),
        ('TableApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TableApp.table'),
        ),
    ]
